# https://taskfile.dev

version: "3.0"

vars:
  REPO_PREFIX: me.knapik
  QUIET: '{{default "-q" .QUIET}}'
  CONTAINER_PRETTIER: tmknom/prettier:2.0.5
  PRETTIERCLI: |-
    docker run --rm \
      -v $PWD:/code \
      -w /code \
      {{.CONTAINER_PRETTIER}}

includes:
  prerequisites:
    taskfile: ./taskfile/prerequisites.{{OS}}.yml
    dir: .
  c00:
    taskfile: ./00_size/Taskfile.yml
    dir: 00_size
  c01:
    taskfile: ./01_stages/Taskfile.yml
    dir: 01_stages
  c02:
    taskfile: ./02_entrypoint/Taskfile.yml
    dir: 02_entrypoint
  c03:
    taskfile: ./03_alpine/Taskfile.yml
    dir: 03_alpine
  c04:
    taskfile: ./04_lint/Taskfile.yml
    dir: 04_lint
  c05:
    taskfile: ./05_pid1/Taskfile.yml
    dir: 05_pid1
  c06:
    taskfile: ./06_volumes/Taskfile.yml
    dir: 06_volumes
  c07:
    taskfile: ./07_caching/Taskfile.yml
    dir: 07_caching
  c08:
    taskfile: ./08_inception/Taskfile.yml
    dir: 08_inception
  c09:
    taskfile: ./09_traefik/Taskfile.yml
    dir: 09_traefik
  c10:
    taskfile: ./10_performance/Taskfile.yml
    dir: .

tasks:
  default:
    cmds:
      - task: c00
      - task: c01
      - task: c02
      - task: c03
      - task: c04
      - task: c05
      - task: c06
      - task: c07
      - task: c08
      - task: c09

  c00: { cmds: [{ task: c00:default }] }
  c01: { cmds: [{ task: c01:default }] }
  c02: { cmds: [{ task: c02:default }] }
  c03: { cmds: [{ task: c03:default }] }
  c04: { cmds: [{ task: c04:default }] }
  c05: { cmds: [{ task: c05:default }] }
  c06: { cmds: [{ task: c06:default }] }
  c07: { cmds: [{ task: c07:default }] }
  c08: { cmds: [{ task: c08:default }] }
  c09: { cmds: [{ task: c09:default }] }
  c10: { cmds: [{ task: c10:default }] }

  prerequisites:
    desc: "Installs all external dependencies using OS package manager."
    cmds:
      - task: prerequisites:all
  prerequisites:all:
    deps:
      - prerequisites:docker
      - prerequisites:hyperfine
      - prerequisites:dive
      - prerequisites:prettier

  format:
    cmds:
      - '{{.PRETTIERCLI}} --write "**/*.{js,jsx,ts,tsx,css,less,scss,vue,json,gql,md,yml,yaml}"'
