version: "3.8"

services:
  server:
    image: me.knapik/server:dev
    build:
      context: server
      target: dev
    init: true
    volumes:
      - ./server:/code:ro
      - node_modules_server:/code/node_modules
      - dist:/code/dist
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.rule=Host(`server.knapik.local`)
      - traefik.http.routers.server.entrypoints=web

  frontend:
    image: me.knapik/frontend:builder
    build:
      context: frontend
      target: builder
    init: true
    volumes:
      - ./frontend:/code:ro
      - node_modules_frontend:/code/node_modules
      - build:/code/public
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`frontend.knapik.local`)
      - traefik.http.routers.frontend.entrypoints=web

  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      #- --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  dist:
  build:
  node_modules_server:
  node_modules_frontend:
