version: "3.8"

services:
  server:
    image: me.knapik/server:dev
    build:
      context: server
      target: dev
    volumes:
      - ./server:/code:ro
      - node_modules_server:/code/node_modules
      - dist:/code/dist
    # ports:
    #   - 8001:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`server.knapik.local`)
      - traefik.http.routers.backend.entrypoints=web

  frontend:
    image: me.knapik/frontend:builder
    build:
      context: frontend
      target: static
    environment:
      - HOST=frontend
    volumes:
      - ./frontend:/code:ro
      - node_modules_frontend:/code/node_modules
      - build:/code/public/build
    # ports:
    #   - 8002:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.svelte.rule=Host(`frontend.knapik.local`)
      - traefik.http.routers.svelte.entrypoints=web

  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      #- --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  dist:
  build:
  node_modules_server:
  node_modules_frontend:
