version: "3.0"

vars:
  REPO_PREFIX: me.knapik
  QUIET: '{{default "-q" .QUIET}}'
  CONTAINER_PRETTIER: tmknom/prettier:2.0.5
  PRETTIERCLI: |-
    docker run --rm \
      -v $PWD:/code \
      -w /code \
      {{.CONTAINER_PRETTIER}}

tasks:
  default:
    cmds:
      - task: size:ubuntu
      - task: size:alpine
      - task: size:build-time-deps

  size:ubuntu:build:
    cmds:
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/size-ubuntu:big --target=a .
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/size-ubuntu:same --target=b .
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/size-ubuntu:not-quite --target=c .
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/size-ubuntu:small --target=d .
    dir: ubuntu
  size:ubuntu:
    deps: [size:ubuntu:build]
    cmds:
      - docker images {{.REPO_PREFIX}}/size-ubuntu

  size:alpine:build:
    cmds:
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/size-alpine:big --target=a .
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/size-alpine:same-as-big --target=b .
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/size-alpine:small --target=c .
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/size-alpine:same-as-small --target=d .
    dir: alpine
  size:alpine:
    deps: [size:alpine:build]
    cmds:
      - docker images {{.REPO_PREFIX}}/size-alpine

  size:build-time-deps:build:
    cmds:
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/size-build-time-deps:big --target=a .
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/size-build-time-deps:small --target=b .
    dir: build-time-deps
  size:build-time-deps:
    deps: [size:build-time-deps:build]
    cmds:
      - docker images {{.REPO_PREFIX}}/size-build-time-deps
