version: "3.0"

vars:
  REPO_PREFIX: me.knapik
  QUIET: '{{default "-q" .QUIET}}'
  CONTAINER_PRETTIER: tmknom/prettier:2.0.5
  PRETTIERCLI: |-
    docker run --rm \
      -v $PWD:/code \
      -w /code \
      {{.CONTAINER_PRETTIER}}

tasks:
  default:
    cmds:
      - task: stages:run

  stages:build:
    cmds:
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/stages:builder --target=builder .
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/stages:final --target=final .
    dir: .
  stages:run:
    deps: [stages:build]
    cmds:
      - docker images {{.REPO_PREFIX}}/stages
      - docker run --rm --name stages-final {{.REPO_PREFIX}}/stages:final
