version: "3.8"

networks:
  dind:
volumes:
  ca:
  client:
services:
  dind:
    image: docker:dind
    privileged: true
    networks:
      dind:
        aliases:
          - dind
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ca:/certs/ca
      - client:/certs/client
