version: "3.0"

vars:
  REPO_PREFIX: me.knapik
  QUIET: '{{default "-q" .QUIET}}'
  CONTAINER_PRETTIER: tmknom/prettier:2.0.5
  PRETTIERCLI: |-
    docker run --rm \
      -v $PWD:/code \
      -w /code \
      {{.CONTAINER_PRETTIER}}

tasks:
  default:
    cmds:
      - task: test
      - task: alpine
      - task: alpine:compare-tags
      - task: alpine:list-packages

  alpine:pull:
    cmds:
      - docker pull alpine:{{.TAG}}
  alpine:
    deps: [{ task: alpine:pull, vars: { TAG: "3" } }]
    cmds:
      - docker run --rm alpine:3 ls -lahi /bin /sbin
      - docker run --rm alpine:3 ls --help
      - docker run --rm alpine:3 busybox ls --help

  alpine:compare-tags:
    deps:
      - task: alpine:pull
        vars: { TAG: "latest" }
      - task: alpine:pull
        vars: { TAG: "3" }
      - task: alpine:pull
        vars: { TAG: "3.13" }
      - task: alpine:pull
        vars: { TAG: "3.13.5" }
    cmds:
      - docker images alpine
  alpine:list-packages:
    cmds:
      - docker run --pull always --rm -it alpine sh -c 'apk update && apk list --available | wc -l'
  ubuntu:list-packages:
    cmds:
      - docker run --pull always --rm -it ubuntu sh -c 'apt-get update && apt list | wc -l'
  debian:list-packages:
    cmds:
      - docker run --pull always --rm -it debian sh -c 'apt-get update && apt list | wc -l'
  test:
    cmds:
      - docker pull centos:8
      - docker pull debian:stable
      - docker pull bitnami/minideb
      - docker pull debian:stable-slim
      - docker pull ubuntu:latest
      - docker pull redis
      - docker pull redis:alpine
      - docker pull bitnami/redis
