version: "3.8"

services:
  app:
    build:
      context: .
      target: novolumes
    image: me.knapik/volumes
    command: tail -f /dev/null
    working_dir: /code
    init: true
    user: ${UID:-1000}
    volumes:
      - ./dirs/pre-existing-dir:/code/pre-existing-dir
      - ./dirs/non-existent-dir:/code/non-existent-dir
      - ./dirs/pre-existing-dir-2:/etc/apk/
      - ./dirs/non-existent-dir-2:/etc/profile.d/
      - ./dirs/pre-existing-file:/code/pre-existing-file
      # - ./dirs/non-existent-file:/code/c/1
      - ./dirs/pre-existing-dir:/code/read-only:ro
      - a:/code/a
      - c:/code/c
      - e:/code/e


volumes:
  a:
  c:
  e:
