version: "3.8"

services:
  pre-existing:
    image: alpine:3
    command: touch /code/file
    working_dir: /code
    init: true
    user: '1000'
    volumes:
      - ./dirs/pre-existing:/code/
  non-existent-user:
    image: alpine:3
    command: touch /code/file
    working_dir: /code
    init: true
    user: '1000'
    volumes:
      - ./dirs/non-existent-user:/code/
  non-existent-root:
    image: alpine:3
    command: touch /code/file
    working_dir: /code
    init: true
    user: '0'
    volumes:
      - ./dirs/non-existent-root:/code/

  pre-existing-2:
    image: alpine:3
    command: ls /etc/apk/
    working_dir: /code
    init: true
    user: '1000'
    volumes:
      - ./dirs/pre-existing-2:/etc/apk/
  non-existent-user-2:
    image: alpine:3
    command: ls /etc/apk/
    working_dir: /code
    init: true
    user: '1000'
    volumes:
      - ./dirs/non-existent-user-2:/etc/apk/
  non-existent-root:
    image: alpine:3
    command: ls /etc/apk/
    working_dir: /code
    init: true
    user: '0'
    volumes:
      - ./dirs/non-existent-root-2:/etc/apk/
