version: "3.0"

vars:
  REPO_PREFIX: me.knapik
  QUIET: '{{default "-q" .QUIET}}'
  CONTAINER_PRETTIER: tmknom/prettier:2.0.5
  PRETTIERCLI: |-
    docker run --rm \
      -v $PWD:/code \
      -w /code \
      {{.CONTAINER_PRETTIER}}

tasks:
  default:
    cmds:
      - task: volumes

  volumes:build:
    cmds:
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/volumes .
    dir: .
  volumes:
    deps: [volumes:build]
    cmds:
      - docker run --rm {{.REPO_PREFIX}}/volumes
  example:
    cmds:
      - task: example-nonempty-guest
      - task: example-empty-guest
      - task: example-cleanup
  example:cleanup:
    cmds:
      - git clean -fdx
      - tree -apugfi dirs
      - sudo git clean -fdx
      - tree -apugfi dirs
  example:nonempty-guest:
    cmds:
      - tree -apugfi dirs
      - docker-compose up pre-existing-2
      - tree -apugfi dirs
      - docker-compose up non-existent-user-2
      - tree -apugfi dirs
      - docker-compose up non-existent-root-2
      - tree -apugfi dirs
  example:empty-guest:
    cmds:
      - tree -apugfi dirs
      - docker-compose up pre-existing
      - tree -apugfi dirs
      - docker-compose up non-existent-user
      - tree -apugfi dirs
      - docker-compose up non-existent-root
      - tree -apugfi dirs

