version: "3.0"

vars:
  REPO_PREFIX: me.knapik
  QUIET: '{{default "-q" .QUIET}}'
  CONTAINER_PRETTIER: tmknom/prettier:2.0.5
  PRETTIERCLI: |-
    docker run --rm \
      -v $PWD:/code \
      -w /code \
      {{.CONTAINER_PRETTIER}}

tasks:
  default:
    cmds:
      - task: volumes

  volumes:build:
    cmds:
      - docker build {{.QUIET}} -t {{.REPO_PREFIX}}/volumes .
    dir: .
  volumes:
    deps: [volumes:build]
    cmds:
      - docker run --rm {{.REPO_PREFIX}}/volumes
  example:cleanup:
    cmds:
      - tree -apugfi dirs
      - sudo git clean -fdx
      - tree -apugfi dirs
      - docker-compose down --volume --remove-orphans
  example:guest:
    cmds:
      - tree -apugfi dirs
      - docker-compose up -d
      - cmd: docker-compose exec app bash -c 'ls -d /code/*/ | xargs -I {} touch {}/newfile'
        ignore_error: true
      - tree -apugfi dirs
    env:
      UID: 1000
  example:root:
    cmds:
      - tree -apugfi dirs
      - docker-compose up -d
      - cmd: docker-compose exec app bash -c 'ls -d /code/*/ | xargs -I {} touch {}/newfile'
        ignore_error: true
      - tree -apugfi dirs
    env:
      UID: 0

